# Generated by Django 4.2.7 on 2023-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniprojectapp', '0004_rightmsg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rightmsg',
            new_name='rightmsgtable',
        ),
        migrations.RenameField(
            model_name='rightmsgtable',
            old_name='title',
            new_name='name',
        ),
    ]
