# Generated by Django 4.2.7 on 2023-11-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprojectapp', '0005_rename_rightmsg_rightmsgtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstable',
            name='date',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
